---
- name: Template a file to /usr/src
  hosts: aula
  become: yes
  gather_facts: yes
  vars:
    file_src: config.json
    file_dest: /usr/src
    owner: root
    group: root
    mode: 0777
  tasks:
    - name: Upload file
      template:
        src:  "{{file_src}}"
        dest: "{{file_dest}}"
        owner: "{{owner}}"
        group: "{{group}}"
        mode: "{{mode}}"
      register: exercicio
    - name: Replace text
      replace:
        path: '{{file_dest}}/{{file_src}}'
        backup: true
        regexp: "development"
        replace: "production"
      when: exercicio is success